# Generated by Django 3.0.6 on 2020-05-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Урок', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200)),
                ('status', models.CharField(blank=True, choices=[('s', 'student'), ('t', 'teacher')], default='student', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='daily_timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('number_of_lessons', models.CharField(help_text='Количество уроков', max_length=1)),
                ('lessons', models.ManyToManyField(help_text='выберете уроки', to='application.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], help_text='выберете класс', max_length=2)),
                ('the_letter_class', models.CharField(help_text='буква класса', max_length=1)),
                ('students', models.ManyToManyField(help_text='выберите учеников', to='application.Users')),
            ],
        ),
    ]
