# Generated by Django 3.0.6 on 2020-06-01 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='students',
        ),
        migrations.AddField(
            model_name='daily_timetable',
            name='Day',
            field=models.DateField(choices=[('Пн', 'Понедельник'), ('Вт', 'Вторник'), ('Ср', 'Среда'), ('Чт', 'Четверг'), ('Пт', 'Пятница'), ('Сб', 'Суббота'), ('Вс', 'Воскресенье')], default=datetime.date(2020, 6, 1), help_text='выберете день'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='grade',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], help_text='выберете класс', max_length=1),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
