# Generated by Django 3.0.6 on 2020-06-01 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20200601_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_timetable',
            name='Day',
            field=models.CharField(choices=[('Пн', 'Понедельник'), ('Вт', 'Вторник'), ('Ср', 'Среда'), ('Чт', 'Четверг'), ('Пт', 'Пятница'), ('Сб', 'Суббота'), ('Вс', 'Воскресенье')], default=datetime.date(2020, 6, 1), help_text='выберете день', max_length=11),
        ),
    ]
