# Generated by Django 3.0.6 on 2020-06-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20200603_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='student',
            field=models.CharField(choices=[(1, 1), (2, 2)], default='', help_text='ученик', max_length=100),
        ),
        migrations.RemoveField(
            model_name='classes',
            name='students',
        ),
        migrations.AddField(
            model_name='classes',
            name='students',
            field=models.CharField(choices=[(1, 1), (2, 2)], default='', help_text='выберите учеников', max_length=100),
        ),
        migrations.RemoveField(
            model_name='score',
            name='teacher',
        ),
        migrations.AddField(
            model_name='score',
            name='teacher',
            field=models.CharField(choices=[(1, 1), (2, 2)], default='', help_text='учитель', max_length=100),
        ),
    ]
