# Generated by Django 3.0.6 on 2020-06-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20200603_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='students',
            field=models.CharField(choices=[], default='', help_text='выберите учеников', max_length=100),
        ),
    ]
